### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'length' of undefined" when deleting lines

### ISSUE THREAD

**Issue by GustavoDarriens** [jakesankey/line-diff-details#1]
1. Delete a non empty line
2. try to see the diff

**Atom Version**: 0.187.0
**System**: linux 3.13.0-49-generic
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/stu/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:37

TypeError: Cannot read property 'length' of undefined
    at LineDiffWorker.decorateDiffMarkers (/home/stu/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:65:65)
    at HTMLDivElement.<anonymous> (/home/stu/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:55:24)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
line-diff-details, v1.0.0
minimap, v4.7.6

# Dev
No dev packages
```

**Comment by marcusorjames** [comment]
+1 same problem

**Comment by jakesankey** [comment]
This is related to issue #3 as well. I have experienced the issue as well. I will try to look into it ASAP. It seems it only occurs after scrolling which makes it even more odd.

**Comment by iu0v1** [comment]
Hello.
I have similar issue, but with new version of package.
Some details:

    Uncaught TypeError: Cannot read property 'length' of undefined
    C:\Users\lord\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44

stack trace:

	TypeError: Cannot read property 'length' of undefined
	  at LineDiffWorker.decorateDiffMarkers (C:\Users\lord\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44:67)
	  at HTMLDivElement.<anonymous> (C:\Users\lord\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:34:14)
	  at HTMLDivElement.jQuery.event.dispatch (C:\Users\lord\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
	  at HTMLDivElement.elemData.handle (C:\Users\lord\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

platform: windows, atom ver: 0.199.0, line-diff-details: 1.1.1;

Open a new issue, or leave this information here?

**Comment by jakesankey** [comment]
Go ahead and open a new issue. How can I reproduce the issue?

**Comment by sebet** [comment]
I'm still getting this error (v.1.1.2):
```
TypeError: Cannot read property 'length' of null
  at LineDiffWorker.findDiffForLine (/Users/bcarreco/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:74:9)
  at LineDiffWorker.calculateDiffDetails (/Users/bcarreco/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:84:20)
  at HTMLDivElement.<anonymous> (/Users/bcarreco/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
  at HTMLDivElement.jQuery.event.dispatch (/Users/bcarreco/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Users/bcarreco/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
Thanks for looking and congrats on the idea.

**Comment by jakesankey** [comment]
@sebet - Could you please provide some insights as to your setup. I am still unable to reproduce this issue. Do you have multiple git projects open in the same atom workspace?

**Comment by sebet** [comment]
Yes. So, I have the `Project Manager` package installed and I my settings are sometigng like this:

```
myproject:
  title: "myproject"
  group: "mygroup"
  paths: [
      "/.../myfolder1"
      ".../myfolder2"
  ]
```

Let me know if you need more details.

**Comment by jakesankey** [comment]
Both projects are git projects?

**Comment by sebet** [comment]
Yes.

**Comment by sebet** [comment]
When disabling the `Project Manager` package and creating a new project through `Add Project Folder` the issues disappears.

**Comment by jakesankey** [comment]
I am still unable to reproduce the issue. Perhaps it is something with Project Manager plugin...
