### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by nkovacs** [jakesankey/line-diff-details#11]
This happens when I have files that are modified in my working copy, and I try to split a pane.

**Atom Version**: 1.2.0
**System**: Ubuntu 15.10
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.1.3

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
  at Object.global.__grim__.deprecate (/usr/share/atom/resources/app.asar/node_modules/grim/lib/grim.js:56:36)
  at TextEditor.module.exports.TextEditor.onDidChangeScrollTop (/usr/share/atom/resources/app.asar/src/text-editor.js:375:12)
  at LineDiffWorker.registerEditor (/home/nkovacs/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:5:17)
  at /home/nkovacs/.atom/packages/line-diff-details/lib/line-diff-details.ts:8:28
  at /usr/share/atom/resources/app.asar/src/workspace.js:287:16
  at /usr/share/atom/resources/app.asar/src/workspace.js:352:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:375:27)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:353:19
  at /usr/share/atom/resources/app.asar/src/pane-container.js:97:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/usr/share/atom/resources/app.asar/src/pane-container.js:293:27)
  at Pane.module.exports.Pane.setContainer (/usr/share/atom/resources/app.asar/src/pane.js:98:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/usr/share/atom/resources/app.asar/src/pane-axis.js:144:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/usr/share/atom/resources/app.asar/src/pane-axis.js:216:19)
  at Pane.module.exports.Pane.split (/usr/share/atom/resources/app.asar/src/pane.js:706:23)
  at Pane.module.exports.Pane.splitRight (/usr/share/atom/resources/app.asar/src/pane.js:668:19)
  at atom-pane.commandRegistry.add.pane:split-right (/usr/share/atom/resources/app.asar/src/register-default-commands.js:194:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:99:36)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -0:08.4.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:05.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.3.0 pane:split-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "buffer-pos"
    ],
    "disabledPackages": [
      "language-jade",
      "linter-jade"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
buffer-pos, v0.3.0
editorconfig, v1.2.2
go-plus, v3.5.2
go-rename, v0.3.0
highlight-selected, v0.11.1
line-diff-details, v1.1.3
linter, v1.11.1
linter-eslint, v5.1.0
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
nuclide-file-watcher, v0.0.32
nuclide-flow, v0.0.32

# Dev
No dev packages
```

**Comment by jakesankey** [comment]
This should have been resolved in a previous update. Please reopen if I am incorrect.
