### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jesseteal** [jakesankey/line-diff-details#16]
[Enter steps to reproduce below:]

1. click gutter highlight

**Atom Version**: 1.5.3
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /C:/Users/jteal/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:122

TypeError: Cannot read property 'replace' of undefined
    at LineDiffWorker.findFileDiffs (file:///C:/Users/jteal/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:67:110)
    at LineDiffWorker.calculateDiffDetails (file:///C:/Users/jteal/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:84:22)
    at HTMLDivElement.<anonymous> (file:///C:/Users/jteal/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\jteal\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\jteal\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-cfml, v0.12.0
line-diff-details, v1.2.0
minimap, v4.19.0
minimap-git-diff, v4.1.8
project-manager, v2.7.6
python-tools, v0.6.7
svn, v0.0.9

# Dev
No dev packages
```

**Comment by caeldom** [comment]
Having the same issue.

line-diff-details 1.2.0
Atom 1.6.0
Windows 10

```
Uncaught TypeError: Cannot read property 'replace' of undefined
/C:/Users/dan.lim/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:122

TypeError: Cannot read property 'replace' of undefined
    at LineDiffWorker.findFileDiffs (file:///C:/Users/dan.lim/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:67:110)
    at LineDiffWorker.calculateDiffDetails (file:///C:/Users/dan.lim/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:84:22)
    at HTMLDivElement.<anonymous> (file:///C:/Users/dan.lim/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\dan.lim\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\dan.lim\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```
**Installed Packages**
>C:\Users\dan.lim\.atom\packages (21)
├── an-old-hope-syntax@0.5.0
├── atom-beautify@0.28.27
├── atom-material-syntax@0.4.5
├── atom-monokai@0.10.1
├── autoclose-html@0.23.0
├── file-icons@1.6.19
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── line-diff-details@1.2.0
├── linter@1.11.4
├── linter-jshint@2.0.3
├── minimap@4.21.0
├── minimap-cursorline@0.1.0
├── minimap-find-and-replace@4.5.0
├── minimap-git-diff@4.2.0
├── minimap-highlight-selected@4.4.0
├── minimap-selection@4.4.0
├── open-recent@5.0.0
├── recent-files-fuzzy-finder@0.2.4
├── Sublime-Style-Column-Selection@1.5.1
└── svn@0.0.9
