### ISSUE TITLE
Failed to activate the line-diff-details package

### ISSUE THREAD

**Issue by FezVrasta** [jakesankey/line-diff-details#23]
Just opening the Atom editor...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.3.4

### Stack Trace

Failed to activate the line-diff-details package

```
At Cannot read property 'onDidChangeScrollTop' of null

TypeError: Cannot read property 'onDidChangeScrollTop' of null
    at LineDiffWorker.registerEditor (/Users/federicozivolo/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:5:30)
    at /Users/federicozivolo/.atom/packages/line-diff-details/lib/line-diff-details.ts:7:28
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:307:9)
    at LineDiffDetails.activate (/Users/federicozivolo/.atom/packages/line-diff-details/lib/line-diff-details.ts:5:24)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "selection-highlight",
      "tree-view-git-modified",
      "project-dropdown",
      "recent-projects",
      "project-manager",
      "project-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
auto-indent, v0.5.0
editorconfig, v1.4.1
highlight-selected, v0.11.2
language-stylus, v0.2.0
line-diff-details, v1.3.4
linter, v1.11.4
linter-eslint, v7.2.2
linter-jshint, v2.1.0
markdown-table-formatter, v2.8.3
open-recent, v5.0.0
project-viewer, v0.2.32
react, v0.15.0
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by marcusorjames** [comment]
Bump

**Comment by chalda** [comment]
also getting this.

**Comment by jakesankey** [comment]
Bah. Sorry all. I just published a new version. Hope it works for ya.

**Comment by Windstalker** [comment]
Same issue again. Atom v.1.15

**Comment by Windstalker** [comment]
@jakesankey bump

**Comment by kielnino** [comment]
Same here, at Atom startup...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Linux Mint
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.6.0


### Stack Trace

Failed to activate the line-diff-details package

```
At Cannot read property 'onDidChangeScrollTop' of null

TypeError: Cannot read property 'onDidChangeScrollTop' of null
    at LineDiffWorker.registerEditor (/home/xxxx/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:7:30)
    at /home/xxxx/.atom/packages/line-diff-details/lib/line-diff-details.ts:11:28
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:330:9)
    at LineDiffDetails.activate (/home/xxxx/.atom/packages/line-diff-details/lib/line-diff-details.ts:9:24)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:779:28
```

**Comment by petrjaros** [comment]
@kielnino Clearing a cache worked for me. I deleted whole directory `C:\Users\xxx\AppData\Roaming\Atom` on Windows. And everything works for me now. Don't know the location on Linux, but it contains following folders: `databases, GPUCache, IndexedDB, Local Storage`.

**Comment by sesperanto** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package 1.6.0


### Stack Trace

Failed to activate the line-diff-details package

```
At Cannot read property 'onDidChangeScrollTop' of null

TypeError: Cannot read property 'onDidChangeScrollTop' of null
    at LineDiffWorker.registerEditor (/packages/line-diff-details/lib/line-diff-worker.coffee:7:30)
    at /packages/line-diff-details/lib/line-diff-details.ts:11:28
    at Workspace.module.exports.Workspace.observeTextEditors (/app.asar/src/workspace.js:329:9)
    at LineDiffDetails.activate (/packages/line-diff-details/lib/line-diff-details.ts:9:24)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.3.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
language-haml 0.24.1 
line-diff-details 1.6.0 
linter 2.1.2 
linter-erb 1.0.4 
linter-haml 2.0.1 
linter-ruby 1.2.5 
linter-ui-default 1.2.2 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
pigments 0.39.1 
rails-i18n-autocomplete 0.4.0 
react 0.16.2 
seti-icons 1.4.3 
split-diff 1.3.0 
todo-show 1.11.0 
tree-view-git-status 1.3.1 
```

**Comment by skladd** [comment]
@petrjaros 
Clearing cache worked for me, too.
Linux path is `$HOME/.config/Atom`

**Comment by fones** [comment]
After updating I got the same error.

Then I have removed this package, and install it again. (Clean install)

It works. On Mac.

**Comment by Gkupce** [comment]
The problem seems to come from config in the file ``[AppData\Roaming\]Atom\IndexedDB\file__0.indexeddb.leveldb\MANIFEST-000001`` \[in windows\]. This is specially bad as it is also the file that contains which files you had open last session, so deleting it is not an option for most people.
Tried the clean install, but it didn't work for me in windows.

**Comment by skousong** [comment]
Closing all files and restarting seemed to clear it up for me.

**Comment by me6iaton** [comment]
Then I have removed this package, and install it again. (Clean install) - not work for me,  on Mac.
