### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by subesokun** [jakesankey/line-diff-details#3]
1. Modify any line
2. Click on the line number to show the line-diff

**Atom Version**: 0.198.0
**System**: linux 3.16.0-37-generic
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /home/subesokun/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:66

TypeError: Cannot read property 'length' of null
  at LineDiffWorker.findDiffForLine (/home/subesokun/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:66:9)
  at LineDiffWorker.calculateDiffDetails (/home/subesokun/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:75:20)
  at HTMLDivElement.<anonymous> (/home/subesokun/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:30:24)
  at HTMLDivElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:04.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:04.1.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.14.1
docblockr, v0.6.3
editorconfig, v1.0.0
file-icons, v1.5.5
line-diff-details, v1.0.0
linter, v0.12.2
linter-jshint, v0.1.4
minimap, v4.8.0
minimap-git-diff, v4.1.2
monokai, v0.14.0
project-manager, v1.15.5
project-view, v0.1.2
revert-buffer, v0.5.0

# Dev
No dev packages
```

**Comment by marcusorjames** [comment]
Unfortunately I am getting this bug again, was fixed for ages but doing same thing again:

[Enter steps to reproduce below:]

1. Modify line
2. click line number

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:147

TypeError: Cannot read property 'length' of null
    at LineDiffWorker.findDiffForLine (file:///C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:78:9)
    at LineDiffWorker.calculateDiffDetails (file:///C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:88:20)
    at HTMLDivElement.<anonymous> (file:///C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\marcus\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\marcus\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -1:08.9.0 symbols-view:return-from-declaration (atom-text-editor.editor.is-focused)
     -0:57.6.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:37.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:37.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:37.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:37.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:37.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:36.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:36.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:36.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:36.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:35.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  5x -0:22.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:19.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-autocomplete-php, v0.18.4
atom-beautify, v0.28.21
change-case, v0.6.0
docblockr, v0.7.3
emmet, v2.3.17
file-icons, v1.6.13
fold-functions, v0.4.3
highlight-selected, v0.11.1
last-cursor-position, v0.9.0
line-diff-details, v1.2.0
linter, v1.11.3
linter-jshint, v1.2.2
linter-php, v1.1.6
minimap, v4.19.0
minimap-git-diff, v4.1.8
php-cs-fixer, v2.5.2
php-twig, v4.0.0
project-manager, v2.7.3
sass-watch, v0.3.1
symbol-gen, v1.0.0
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by MattiJarvinen** [comment]
Same here, worked before.

**Comment by mdesign83** [comment]
+1

**Comment by veegee2** [comment]
I now install the new empty atom 1.4.1 and add only line-diff and get the same error
/C:/Users/Petr2/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:147
Hide Stack Trace
TypeError: Cannot read property 'length' of null
    at LineDiffWorker.findDiffForLine (file:///C:/Users/Petr2/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:78:9)
    at LineDiffWorker.calculateDiffDetails (file:///C:/Users/Petr2/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:88:20)
    at HTMLDivElement.<anonymous> (file:///C:/Users/Petr2/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\Petr2\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\Petr2\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)

**Comment by llagerlof** [comment]
Same problem here.
Windows 8 x64, Atom 1.5.1, line-diff-details 1.2.0.

**Comment by LemonQ** [comment]
Problem still presented
Windows 7 x64, Atom 1.5.3, line-diff-details 1.2.0

**Comment by Ezkivel** [comment]
Same problem .
Windows 10 x64, Atom 1.5.3, line-diff-details 1.2.0

**Comment by aljinovic** [comment]
Same here, Windows 10 x64, Atom 1.6.1, line-diff-details 1.2.0

**Comment by kbrose** [comment]
@ windows users:

Can you try using the code from PR #17 and see if that fixes your problem?

**Comment by marcusorjames** [comment]
I'm totally getting this bug again :(

**Comment by marcusorjames** [comment]
And still getting this bug! :(

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.3.5


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:147

TypeError: Cannot read property 'length' of null
    at LineDiffWorker.findDiffForLine (file:///C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:78:9)
    at LineDiffWorker.calculateDiffDetails (file:///C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:87:20)
    at HTMLDivElement.<anonymous> (file:///C:/Users/marcus/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\marcus\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\marcus\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -0:32 application:show-settings (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "emmet",
      "atom-autocomplete-php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.29.7
atom-minify, v0.7.4
change-case, v0.6.0
docblockr, v0.7.3
file-icons, v1.7.13
fold-functions, v0.4.3
highlight-selected, v0.11.2
last-cursor-position, v0.9.0
line-diff-details, v1.3.5
linter, v1.11.4
linter-jshint, v2.1.0
linter-php, v1.2.0
minimap, v4.24.3
minimap-git-diff, v4.3.1
php-cs-fixer, v2.5.6
php-debug, v0.2.3
php-getters-setters, v0.5.5
php-twig, v4.0.0
project-manager, v2.9.7
sass-watch, vundefined
symbol-gen, v1.3.0
symbols-tree-view, v0.13.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by a7madgamal** [comment]
same here

**Comment by pebie** [comment]
same her,

problem appears after installing prettier if it can help...

**Comment by sesperanto** [comment]
same here

Atom 1.22.1, line-diff-details 1.9.0

```
/home/sesi/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:87

TypeError: Cannot read property 'length' of null
    at LineDiffWorker.findDiffForLine (/home/sesi/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:87:9)
    at LineDiffWorker.calculateDiffDetails (/home/sesi/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:96:20)
    at HTMLDivElement.<anonymous> (/home/sesi/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:35:24)
    at HTMLDivElement.dispatch (/home/sesi/.atom/packages/line-diff-details/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/home/sesi/.atom/packages/line-diff-details/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by filsh** [comment]
same here
