### ISSUE TITLE
Failed to load the line-diff-details package -- Error: Cannot find module 'jquery'

### ISSUE THREAD

**Issue by colin-kiegel** [jakesankey/line-diff-details#36]
**Steps To Reproduce**

1. start atom

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package 1.5.0

### Stack Trace

Failed to load the line-diff-details package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/line-diff-details/lib/line-diff-details.ts:1:29)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
```

### Non-Core Packages

```
atom-terminal 0.8.0 
autoupdate-packages 1.3.1 
browser-plus 0.0.87 
browser-refresh 0.9.0 
build 0.67.0 
build-cargo 2.0.0 
busy 0.7.0 
cargo-test-runner 0.1.0 
docblockr 0.9.1 
firewatch-syntax 1.1.1 
git-control 0.8.2 
git-history 3.2.0 
git-log 0.4.1 
git-plus 7.3.3 
git-time-machine 1.5.6 
gruvbox-plus-syntax 1.3.1 
imdone-atom 2.1.21 
language-rust 0.4.9 
line-diff-details 1.5.0 
linter 1.11.23 
linter-rust 0.7.2 
linter-tidy 2.3.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-git-diff 4.3.1 
platformio-ide-terminal 2.4.0 
project-manager 3.3.3 
racer 0.20.0 
rust-api-docs-helper 0.5.1 
theme-switcher 1.1.0 
tool-bar 1.0.1 
travis-ci-status 1.3.1 
```

**Comment by colin-kiegel** [comment]
Initially the problem started after upgrading atom. Today I decided to re-install this package. This solved the problem for me. :-)
