### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'length' of undefined" when deleting lines

### ISSUE THREAD

**Issue by aaubry** [jakesankey/line-diff-details#4]
This seems to be a duplicate of #1, but since it has been closed, I choose to open a new issue. I could not find any workaround to this problem. 

[Enter steps to reproduce below:]

1. Add a project folder that is a git repository
2. Make changes to a file
3. Attempt to see any changes.

**Atom Version**: 0.202.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Antoine Aubry\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44

TypeError: Cannot read property 'length' of undefined
  at LineDiffWorker.decorateDiffMarkers (C:\Users\Antoine Aubry\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44:67)
  at HTMLDivElement.<anonymous> (C:\Users\Antoine Aubry\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:34:14)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\Antoine Aubry\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (C:\Users\Antoine Aubry\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -1:14.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:09.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.3.0 git-log:show (atom-text-editor.editor)
     -1:08.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:51.7.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -0:46 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
git-log, v0.4.1
language-powershell, v2.0.1
language-puppet, v0.12.0
line-diff-details, v1.1.1
remote-edit, v1.7.2

# Dev
No dev packages
```

**Comment by kankaristo** [comment]
Happening for me too. Atom's "Create issue" button points to #3.

I have a slightly different stack trace:
```
TypeError: Cannot read property 'length' of null
  at LineDiffWorker.findDiffForLine (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:74:9)
  at LineDiffWorker.calculateDiffDetails (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:84:20)
  at HTMLDivElement.<anonymous> (/home/sami/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
  at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by Gkupce** [comment]
I'll add my stack trace.
Happens on any kind of modification.

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.1.1


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Stavo\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44

TypeError: Cannot read property 'length' of undefined
  at LineDiffWorker.decorateDiffMarkers (C:\Users\Stavo\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:44:67)
  at HTMLDivElement.<anonymous> (C:\Users\Stavo\.atom\packages\line-diff-details\lib\line-diff-worker.coffee:34:14)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\Stavo\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (C:\Users\Stavo\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-shadercode, v2.0.0
line-diff-details, v1.1.1
minimap, v4.10.2
seti-icons, v0.3.0

# Dev
No dev packages
```
