### ISSUE TITLE
Failed to load the line-diff-details package

### ISSUE THREAD

**Issue by khaledalyawad** [jakesankey/line-diff-details#48]
1. I just tried to install the plugin 

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package 1.9.0

### Stack Trace

Failed to load the line-diff-details package

```
At ENOENT, node_modules/typescript/bin/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar

Error: ENOENT, node_modules/typescript/bin/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:513:9)
    at TypeScriptSimple.createService (/Applications/Atom.app/Contents/Resources/app/node_modules/typescript-simple/index.js:71:73)
    at TypeScriptSimple.compile (/Applications/Atom.app/Contents/Resources/app/node_modules/typescript-simple/index.js:60:43)
    at Object.exports.compile (/Applications/Atom.app/Contents/Resources/app/src/typescript.js:54:53)
    at Object.compile (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:79:33)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:98:37)
    at Object.value [as .ts] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:689:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:280:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
     -6:09.7.0 editor:toggle-line-comments (input.hidden-input)
     -6:09.3.0 core:save (input.hidden-input)
  2x -5:45.9.0 find-and-replace:select-next (input.hidden-input)
     -5:28.8.0 editor:newline (input.hidden-input)
     -5:27.7.0 autocomplete-plus:confirm (input.hidden-input)
     -5:27.7.0 snippets:expand (atom-text-editor.editor.typescript-editor.is-focused.autocomplete-active)
     -5:25.3.0 autocomplete-plus:confirm (input.hidden-input)
     -5:24.8.0 core:save (input.hidden-input)
     -3:09.1.0 core:backspace (input.hidden-input)
     -3:07.3.0 core:confirm (input.hidden-input)
     -1:59 editor:newline (input.hidden-input)
     -1:50.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -1:48.9.0 editor:consolidate-selections (input.hidden-input)
     -1:48.9.0 core:cancel (input.hidden-input)
  4x -0:54.4.0 core:backspace (input.hidden-input)
     -0:50.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
atom-typescript 12.3.8 
clipboard-history 0.6.6 
file-icons 2.1.18 
highlight-selected 0.13.1 
line-diff-details 1.9.0 
minimap 4.29.8 
monokai 0.24.0 
platformio-ide-terminal 2.8.1 
vertical-tabs 1.0.7 
```

**Comment by Sod-Almighty** [comment]
Then WHY IS THIS BROKEN PACKAGE STILL ON THE REPO for people to waste their time trying to install?

**Comment by Sod-Almighty** [comment]
I'm getting damn sick of people leaving their broken-arse crap up on the public repo. Either fix it, or take it down!
