### ISSUE TITLE
Uncaught TypeError: Cannot read property 'repo' of null

### ISSUE THREAD

**Issue by dbarrosop** [jakesankey/line-diff-details#6]
I get the following error when trying to click on the number to get the diff.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [line-diff-details](https://github.com/jakesankey/line-diff-details) package, v1.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'repo' of null

```
At /Users/dbarroso/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:66

TypeError: Cannot read property 'repo' of null
  at LineDiffWorker.findFileDiffs (/Users/dbarroso/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:66:83)
  at LineDiffWorker.calculateDiffDetails (/Users/dbarroso/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:80:22)
  at HTMLDivElement.<anonymous> (/Users/dbarroso/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:32:24)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/3d_Party/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Applications/3d_Party/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -4:58.2.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -4:58 core:move-left (atom-text-editor.editor.is-focused)
     -4:57.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:56.8.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -4:56.4.0 editor:add-selection-below (atom-text-editor.editor.is-focused)
     -4:55.4.0 core:move-up (atom-text-editor.editor.is-focused)
  6x -4:55 editor:add-selection-above (atom-text-editor.editor.is-focused)
     -4:53.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:47.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:33 editor:select-line (atom-text-editor.editor.is-focused)
     -4:32 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:32 core:cancel (atom-text-editor.editor.is-focused)
     -4:14.3.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:39.2.0 core:cancel (a.btn-issue.btn.btn-error)
     -1:28.7.0 git-diff:toggle-diff-list (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:40.9.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
line-diff-details, v1.1.1

# Dev
No dev packages
```

**Comment by dbarrosop** [comment]
I find out how to reproduce it. If you open a folder which is not a git repo and then you add a folder that is a git repo you get this issue.

**Comment by xsombra** [comment]
Hi.

At /Users/dbarroso/.atom/packages/line-diff-details/lib/line-diff-worker.coffee:66 you have:
```cofeescript
repo = r for r in atom.project.getRepositories() when activePath.indexOf(r.repo.workingDirectory) != -1
```
but r may be null when ther is a project folder that is not in git. May be you can check if r is not null.
